version: "3.9"

services:
  db:
    image: postgres
    container_name: Postgres
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    container_name: AiohhtpBackend
    image: python:3
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    working_dir: /code
    entrypoint: [ "/bin/bash","/code/entrypoint.sh" ]
    env_file:
      - .env
    depends_on:
      - db
    restart: always
